# fly.toml app configuration file generated for kbtuopen on 2023-04-28T15:50:08+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kbtuopen"
primary_region = "ams"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
