# Generated by Django 4.2 on 2023-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team'),
        ),
    ]
