# Generated by Django 4.2 on 2023-05-04 11:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default=core.models.generate_random_pass, max_length=10),
        ),
    ]
