# Generated by Django 4.2 on 2023-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password_sent_at',
            field=models.DateField(null=True),
        ),
    ]
