# Generated by Django 4.2 on 2023-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_password_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
