# Generated by Django 4.2 on 2023-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_seat_alter_team_password_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_synced_with_dmoj',
            field=models.BooleanField(default=False),
        ),
    ]
