# Generated by Django 4.2 on 2025-11-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team_is_synced_with_dmoj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_open', models.BooleanField(default=True)),
            ],
        ),
    ]
